// <auto-generated />
using BackendApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250302022703_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("BackendApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Country #1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Country #2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Country #3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Country #4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Country #5"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Province #1"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Province #2"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Province #3"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Province #4"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Province #5"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Province #6"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Province #7"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "Province #8"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 3,
                            Name = "Province #9"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 4,
                            Name = "Province #10"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 4,
                            Name = "Province #11"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            Name = "Province #12"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 5,
                            Name = "Province #13"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 5,
                            Name = "Province #14"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 5,
                            Name = "Province #15"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApi.Models.Province", b =>
                {
                    b.HasOne("BackendApi.Models.Country", null)
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendApi.Models.Country", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
